platform :ios, '10.0'
use_modular_headers!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'WLThirdUtilDemo' do
    
    pod 'SVProgressHUD'
    
    pod 'JPush'
    
    pod 'UMCPush'
    
    pod 'UMCCommon'
    
    pod 'UMCSecurityPlugins'
    
    pod 'UMCAnalytics'
    
    pod 'UMCShare/UI'
    
    pod 'UMCShare/Social/WeChat'
    
    pod 'UMCShare/Social/QQ'
    
    pod 'YYCache'
    
    pod 'AliyunOSSiOS'
    pod 'AMapLocation-NO-IDFA'
    pod 'AMap2DMap-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    
    pod 'WLToolsKit/OpenUrl'
    
    pod 'JShare'
    
end



